install.packages(c("combinat", "cowplot", "dplyr", "ggplot2", "ggrepel", "readr", "smartsnp", "scales", "tidyr", "viridis", "sf", "stars", "rnaturalearth", "devtools"))
devtools::install_github("bodkan/slendr")

library(combinat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(readr)
library(smartsnp)
library(scales)
library(tidyr)
library(viridis)
library(sf)
library(stars)
library(rnaturalearth)
library(slendr)
setup_env(agree = TRUE)